-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Outsixer.Enum.Game_update_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "game"

  - Active - column name
  - Created\_at - column name
  - Id - column name
  - Name - column name
  - Updated\_at - column name
  - Word - column name

-}
type Game_update_column
    = Active
    | Created_at
    | Id
    | Name
    | Updated_at
    | Word


list : List Game_update_column
list =
    [ Active, Created_at, Id, Name, Updated_at, Word ]


decoder : Decoder Game_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "active" ->
                        Decode.succeed Active

                    "created_at" ->
                        Decode.succeed Created_at

                    "id" ->
                        Decode.succeed Id

                    "name" ->
                        Decode.succeed Name

                    "updated_at" ->
                        Decode.succeed Updated_at

                    "word" ->
                        Decode.succeed Word

                    _ ->
                        Decode.fail ("Invalid Game_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Game_update_column -> String
toString enum =
    case enum of
        Active ->
            "active"

        Created_at ->
            "created_at"

        Id ->
            "id"

        Name ->
            "name"

        Updated_at ->
            "updated_at"

        Word ->
            "word"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Game_update_column
fromString enumString =
    case enumString of
        "active" ->
            Just Active

        "created_at" ->
            Just Created_at

        "id" ->
            Just Id

        "name" ->
            Just Name

        "updated_at" ->
            Just Updated_at

        "word" ->
            Just Word

        _ ->
            Nothing
