-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Outsixer.Enum.Player_update_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "player"

  - Created\_at - column name
  - Game\_id - column name
  - Id - column name
  - Name - column name
  - Updated\_at - column name

-}
type Player_update_column
    = Created_at
    | Game_id
    | Id
    | Name
    | Updated_at


list : List Player_update_column
list =
    [ Created_at, Game_id, Id, Name, Updated_at ]


decoder : Decoder Player_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "created_at" ->
                        Decode.succeed Created_at

                    "game_id" ->
                        Decode.succeed Game_id

                    "id" ->
                        Decode.succeed Id

                    "name" ->
                        Decode.succeed Name

                    "updated_at" ->
                        Decode.succeed Updated_at

                    _ ->
                        Decode.fail ("Invalid Player_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Player_update_column -> String
toString enum =
    case enum of
        Created_at ->
            "created_at"

        Game_id ->
            "game_id"

        Id ->
            "id"

        Name ->
            "name"

        Updated_at ->
            "updated_at"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Player_update_column
fromString enumString =
    case enumString of
        "created_at" ->
            Just Created_at

        "game_id" ->
            Just Game_id

        "id" ->
            Just Id

        "name" ->
            Just Name

        "updated_at" ->
            Just Updated_at

        _ ->
            Nothing
