-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Outsixer.Object exposing (..)


type Game
    = Game


type Game_aggregate
    = Game_aggregate


type Game_aggregate_fields
    = Game_aggregate_fields


type Game_avg_fields
    = Game_avg_fields


type Game_max_fields
    = Game_max_fields


type Game_min_fields
    = Game_min_fields


type Game_mutation_response
    = Game_mutation_response


type Game_stddev_fields
    = Game_stddev_fields


type Game_stddev_pop_fields
    = Game_stddev_pop_fields


type Game_stddev_samp_fields
    = Game_stddev_samp_fields


type Game_sum_fields
    = Game_sum_fields


type Game_var_pop_fields
    = Game_var_pop_fields


type Game_var_samp_fields
    = Game_var_samp_fields


type Game_variance_fields
    = Game_variance_fields


type Player
    = Player


type Player_aggregate
    = Player_aggregate


type Player_aggregate_fields
    = Player_aggregate_fields


type Player_avg_fields
    = Player_avg_fields


type Player_max_fields
    = Player_max_fields


type Player_min_fields
    = Player_min_fields


type Player_mutation_response
    = Player_mutation_response


type Player_stddev_fields
    = Player_stddev_fields


type Player_stddev_pop_fields
    = Player_stddev_pop_fields


type Player_stddev_samp_fields
    = Player_stddev_samp_fields


type Player_sum_fields
    = Player_sum_fields


type Player_var_pop_fields
    = Player_var_pop_fields


type Player_var_samp_fields
    = Player_var_samp_fields


type Player_variance_fields
    = Player_variance_fields
