-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Outsixer.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Outsixer.Scalar exposing (defaultCodecs)


type alias Id =
    Outsixer.Scalar.Id


type alias Timestamptz =
    Outsixer.Scalar.Timestamptz


codecs : Outsixer.Scalar.Codecs Id Timestamptz
codecs =
    Outsixer.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        }
