-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Game
    = Game


type Game_aggregate
    = Game_aggregate


type Game_aggregate_fields
    = Game_aggregate_fields


type Game_avg_fields
    = Game_avg_fields


type Game_max_fields
    = Game_max_fields


type Game_min_fields
    = Game_min_fields


type Game_mutation_response
    = Game_mutation_response


type Game_stddev_fields
    = Game_stddev_fields


type Game_stddev_pop_fields
    = Game_stddev_pop_fields


type Game_stddev_samp_fields
    = Game_stddev_samp_fields


type Game_sum_fields
    = Game_sum_fields


type Game_var_pop_fields
    = Game_var_pop_fields


type Game_var_samp_fields
    = Game_var_samp_fields


type Game_variance_fields
    = Game_variance_fields
