-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Games
    = Games


type Games_aggregate
    = Games_aggregate


type Games_aggregate_fields
    = Games_aggregate_fields


type Games_avg_fields
    = Games_avg_fields


type Games_max_fields
    = Games_max_fields


type Games_min_fields
    = Games_min_fields


type Games_mutation_response
    = Games_mutation_response


type Games_stddev_fields
    = Games_stddev_fields


type Games_stddev_pop_fields
    = Games_stddev_pop_fields


type Games_stddev_samp_fields
    = Games_stddev_samp_fields


type Games_sum_fields
    = Games_sum_fields


type Games_var_pop_fields
    = Games_var_pop_fields


type Games_var_samp_fields
    = Games_var_samp_fields


type Games_variance_fields
    = Games_variance_fields
