-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Api.Scalar.Id


type alias Timestamptz =
    Api.Scalar.Timestamptz


codecs : Api.Scalar.Codecs Id Timestamptz
codecs =
    Api.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        }
