-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Outsixer.Object.Game exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Outsixer.InputObject
import Outsixer.Interface
import Outsixer.Object
import Outsixer.Scalar
import Outsixer.ScalarCodecs
import Outsixer.Union


active : SelectionSet Bool Outsixer.Object.Game
active =
    Object.selectionForField "Bool" "active" [] Decode.bool


created_at : SelectionSet Outsixer.ScalarCodecs.Timestamptz Outsixer.Object.Game
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (Outsixer.ScalarCodecs.codecs |> Outsixer.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


id : SelectionSet Int Outsixer.Object.Game
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Outsixer.Object.Game
name =
    Object.selectionForField "String" "name" [] Decode.string


updated_at : SelectionSet Outsixer.ScalarCodecs.Timestamptz Outsixer.Object.Game
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (Outsixer.ScalarCodecs.codecs |> Outsixer.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)
