-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Outsixer.Object.Player exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Outsixer.InputObject
import Outsixer.Interface
import Outsixer.Object
import Outsixer.Scalar
import Outsixer.ScalarCodecs
import Outsixer.Union


created_at : SelectionSet Outsixer.ScalarCodecs.Timestamptz Outsixer.Object.Player
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (Outsixer.ScalarCodecs.codecs |> Outsixer.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


{-| An object relationship
-}
game : SelectionSet decodesTo Outsixer.Object.Game -> SelectionSet decodesTo Outsixer.Object.Player
game object_ =
    Object.selectionForCompositeField "game" [] object_ identity


game_id : SelectionSet Int Outsixer.Object.Player
game_id =
    Object.selectionForField "Int" "game_id" [] Decode.int


id : SelectionSet Int Outsixer.Object.Player
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Outsixer.Object.Player
name =
    Object.selectionForField "String" "name" [] Decode.string


role : SelectionSet (Maybe String) Outsixer.Object.Player
role =
    Object.selectionForField "(Maybe String)" "role" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet Outsixer.ScalarCodecs.Timestamptz Outsixer.Object.Player
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (Outsixer.ScalarCodecs.codecs |> Outsixer.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)
