module Word exposing (randomWord)

import Random


randomWord : Random.Generator String
randomWord =
    Random.uniform "Outsixer" words


words : List String
words =
    [ "thoughtbot"
    , "book"
    , "coffee mug"
    , "drip"
    , "board game"
    , "covid 19"
    , "house"
    , "dongle"
    , "political solicitation"
    , "Succulent"
    , "Firetruck"
    , "friend"
    , "steak"
    , "green"
    , "Bob Ross"
    , "Cinco de Mayo"
    , "card"
    , "window"
    , "yoga block"
    , "easer"
    , "high school"
    , "waffle"
    , "pancake"
    , "program"
    , "speed boat"
    , "taco"
    , "copper"
    , "punk rock"
    , "london"
    , "bridge"
    , "teusday"
    , "power"
    , "dj"
    , "keyboard"
    , "heart"
    , "breath"
    , "wheel"
    , "cheese"
    , "tear"
    , "mind"
    , "kitten"
    , "a basket of kittens"
    , "lollipop"
    , "numbers"
    , "ball"
    , "chest"
    , "ocean"
    , "river"
    , "grill"
    , "the welsh language"
    , "DNA"
    , "human"
    , "salt"
    , "standup"
    , "retro"
    , "planning"
    , "computer"
    , "pear"
    , "arm"
    , "bear"
    , "dog"
    , "France"
    , "joy"
    , "pillow"
    , "apartment"
    , "quarenteen"
    , "copywriter"
    , "product"
    , "product market fit"
    , "syrup"
    , "minium viable product"
    , "pen"
    , "pencil"
    , "paper"
    , "bell tower"
    , "door"
    , "kitchen"
    , "potatoe"
    , "dirt"
    , "butt"
    , "box"
    , "burn"
    , "mountain"
    , "bar"
    , "teddy bear"
    , "squid"
    , "cocktail"
    ]
