-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Game_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "game"

  - Games\_pkey - unique or primary key constraint

-}
type Game_constraint
    = Games_pkey


list : List Game_constraint
list =
    [ Games_pkey ]


decoder : Decoder Game_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "games_pkey" ->
                        Decode.succeed Games_pkey

                    _ ->
                        Decode.fail ("Invalid Game_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Game_constraint -> String
toString enum =
    case enum of
        Games_pkey ->
            "games_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Game_constraint
fromString enumString =
    case enumString of
        "games_pkey" ->
            Just Games_pkey

        _ ->
            Nothing
